"""Initial schema — full spec/02 data model.

Greenfield: models.py is the single source of truth; this migration materializes
it via create_all. Subsequent migrations are normal autogenerated diffs.
"""

from alembic import op

from relearn_db.models import Base

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    Base.metadata.create_all(op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(op.get_bind())
